spring:
  application:
    name: CyberCordon
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CyberCordon?characterEncoding=utf-8
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      password:
